### ISSUE TITLE
Add example for OR condition in custom filter

### ISSUE THREAD

**Issue by EwoutH** [gboeing/osmnx-examples#90]
I would be curious on how to do more advanced custom filters, for example how to combine two (in and OR fasion).

```Python
custom_filter = '["highway"~"motorway|motorway_link"]'
construction_filter = '["construction"~"motorway|motorway_link"]'
full_filter = ???
```

Possible syntax and examples of more advanced custom filter could be added to [08-custom-filters-infrastructure.ipynb](https://github.com/gboeing/osmnx-examples/blob/main/notebooks/08-custom-filters-infrastructure.ipynb)

**Comment by EwoutH** [comment]
Taking a look back at an old notebook I once applied this trick:

```Python
road_types = '["highway"~"motorway|trunk|primary|secondary|tertiary|motorway_link|trunk_link|primary_link|secondary_link|tertiary_link|construction"]["construction"!~"unclassified|residential|living_street|road|raceway|pedestrian|service|track|bridleway|cycleway|footway|path|steps"]'
```
But I think this should be able to done more elegant and robust.

**Comment by gboeing** [comment]
So an Overpass Turbo query to perform a [union operation](https://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#The_union_operator:_combining_results_and_forming_sets) looks something [like this](https://overpass-turbo.eu/s/1ObX):

```
(way["railway"="light_rail"]({{bbox}});way["highway"="primary"]({{bbox}}););(._;>;);out;
```

This example will return all the ways tagged railway=light_rail and all the ways tagged highway=primary. As you might notice, this doesn't work with the OSMnx `custom_filter` function argument, because that argument is only the `["railway"="light_rail"]` *or* the `["highway"="primary"]` part of the above query.

So then how to you create a graph of the union of multiple infrastructure types? See [here](https://stackoverflow.com/a/62720802/7321942) and [here](https://stackoverflow.com/a/62239377/7321942). The short story is you use `networkx.compose` like:

```python
import networkx as nx
import osmnx as ox
place = 'Some City'
G1 = ox.graph_from_place(place, custom_filter='["highway"~"primary"]')
G2 = ox.graph_from_place(place, custom_filter='["railway"~"light_rail"]')
G = nx.compose(G1, G2)
```

This will generate essentially the same result as the OverpassQL union above.

All that said, it's worth noting that the OSMnx `features` module allows you to pass a `tags` dict argument that *does* allow unions in the query. The `graph` module in contrast queries by predefined `network_type` strings or by inserting a single `custom_filter` string into the query. It may be possible to enhance the `graph` module's functions to accept a `tags` argument (perhaps instead of the `custom_filter` argument), like the `features` module does. But that functionality doesn't currently exist and its feasibility has not been verified.

**Comment by gboeing** [comment]
See also https://github.com/gboeing/osmnx/issues/1199

**Comment by HDKMP** [comment]
Thank you for your eMail!

I am on travel with limited email access until the end of August. In urgent matters regarding activities at KISD, please be in touch with our secretariat via eMail office(at)kisd.de

Thank you very much!

Prof. Philipp Heidkamp, KISD (Köln International School of Design)
